export enum Service {
  news = 'news',
}

export enum ModelType {
  COMMENT = 1,
  TOPIC = 5,
  BOOK = 2,
  NEWS = 4,
  BlogPost = 8,
}

export enum ReactionType {
  LIKE = 'LIKE',
  DISLIKE = 'DISLIKE',
}

export enum Permission {
  OP_ADD_UPDATE_CATEGORY = 'OP_ADD_UPDATE_CATEGORY',
  OP_ADD_UPDATE_TOPIC = 'OP_ADD_UPDATE_TOPIC',
  OP_READ = 'OP_READ',
  OP_AUTHORS_REPORT = 'OP_AUTHORS_REPORT',
  OP_TOPIC_MESSAGE_REPORT = 'OP_TOPIC_MESSAGE_REPORT',
  OP_ADD_UPDATE_ROLE = 'OP_ADD_UPDATE_ROLE',
  OP_PUBLISH_UNPUBLISH_NEWS = 'OP_PUBLISH_UNPUBLISH_NEWS',
  OP_ADD_UPDATE_AUTHOR = 'OP_ADD_UPDATE_AUTHOR',
  OP_TOPIC_MESSAGE_PUBLISH = 'OP_TOPIC_MESSAGE_PUBLISH',
  OP_TOPIC_REPORT = 'OP_TOPIC_REPORT',
  OP_ADD_ROLE_TO_USER = 'OP_ADD_ROLE_TO_USER',
  OP_ADD_UPDATE_BOOK = 'OP_ADD_UPDATE_BOOK',
  OP_ADD_UPDATE_NEWS = 'OP_ADD_UPDATE_NEWS',
  OP_BOOK_REPORT = 'OP_BOOK_REPORT',
  OP_USER_REPORT = 'OP_USER_REPORT',
  OP_PUBLISHER_REPORT = 'OP_PUBLISHER_REPORT',
  OP_ADD_UPDATE_PUBLISHER = 'OP_ADD_UPDATE_PUBLISHER',
  OP_ADD_TAG = 'OP_ADD_TAG',
  OP_BLOCK_UNBLOCK_USER = 'OP_BLOCK_UNBLOCK_USER',
  OP_NEWS_REPORT = 'OP_NEWS_REPORT',
}

export const defaultPagination = { pageIndex: 0, pageSize: 10 };
