import Providers from '@/Providers';
import clsx from 'clsx';
import type { Metadata } from 'next';
import 'vazirmatn/Vazirmatn-font-face.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" dir="rtl" data-theme="light">
      <body className={clsx('flex flex-col px-12')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
